name: Action Self-Tests
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_dispatch:
jobs:
  simple-success:
    strategy:
      matrix:
        version: [ "1.0.0", "1.2", "1.2.1", "1.2.2", "1.2.3", "1.2.4" ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Extract Release Notes
        id: extract
        uses: rvesse/extract-release-notes-action@v1
        with:
          changelog-file: test-data/simple.md
          version: ${{ matrix.version }}
          fail-if-missing: true

      - name: Fail if no release notes output
        if: ${{ steps.extract.outputs.release-notes-file }}
        run: |
          exit 1

      - name: Add release notes to job summary
        run: |
          cat "${{ steps.extract.outputs.release-notes-file }}" >> "${GITHUB_STEP_SUMMARY}"
